spring:
  profiles: real-db
  datasource:
    url: jdbc:mariadb://springboot2-restapi-rds.c7dlmgaionmk.ap-northeast-2.rds.amazonaws.com:3306/spring_boot2
    username: sunlee
    password: wjsdur062!
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
