spring:
  profiles:
    active: dev

---

spring:
  profiles: dev

  datasource:
    url: jdbc:h2:tcp://localhost/~/arduino
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true


---

spring.profiles: product
spring.profiles.active: real-db
server:
  port: 8080